// Generated by CoffeeScript 1.10.0
(function() {
  var app, bodyParser, feathers, memory;

  feathers = require('feathers');

  memory = require('feathers-memory')();

  bodyParser = require('body-parser');

  app = feathers();

  app.configure(feathers.rest()).configure(feathers.socketio()).use(bodyParser.json()).use('/values', memory).use('/', feathers["static"](__dirname)).listen(process.env.PORT || 3000);

  console.log('App listening on port 3000, actually');

  console.log('Index at', __dirname + '/static/');

  "memory.create {'name': 'config',\n'type': 'html', 'value': '<script src=\"https://gist.github.com/EderSantana/bd0d940c5c34386b76b6.js\"></script>'},\n(error, data) ->\n  console.log 'created data: ',  data\n\nmemory.create {'name': 'learning-rate',\n'type': 'float', 'value': 0.001}, {}, (error, data) ->\n  console.log 'created data: ',  data\n\nmemory.create {'name': 'gpu_use',\n'type': 'float', 'value': 35}, {}, (error, data) ->\n  console.log 'created data: ',  data";

}).call(this);
